version: '3.9'
services:
  backend:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app

  db:
    image: mongo
    restart: always
    hostname: db-service
    command: mongod --port 3006
    volumes:
      - ./mongo_data:/data/db
    ports: 
      - 3006:3006